<a href="https://colab.research.google.com/github/INFINITY-RUBER/Machine_Learning_A-Z_Hands-On-Python-R-In-Data-Science/blob/master/Part%208%20-%20Deep%20Learning/Section%2039-2%20-%20Artificial%20Neural%20Networks%20(ANN)/Python/artificial_neural_network_metodo%20regresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network-
MODELO CON REGRESION

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [5]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN




In [8]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

Agregar la capa de entrada y la primera capa oculta

![modelo de la red](https://github.com/INFINITY-RUBER/Machine_Learning_A-Z_Hands-On-Python-R-In-Data-Science/blob/master/Part%208%20-%20Deep%20Learning/Section%2039%20-%20Artificial%20Neural%20Networks%20(ANN)/Python/ANN_Architecture.png?raw=true)


In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

Entrenamiento del modelo ANN en el conjunto de entrenamiento

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
# batch_size tamñao de lote

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 187874.7656
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 4030.6292
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 244.5843
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 239.4022
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 233.2798
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 226.0871
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 218.1212
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 209.1650
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 199.3755
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 188.9111
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 177.3769
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - 

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[430.79 431.23]
 [461.8  460.01]
 [465.29 461.14]
 ...
 [472.51 473.26]
 [439.39 438.  ]
 [458.55 463.28]]
