# Data Preprocessing Tools

## Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [15]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values # todas las filas y todas la culumnas menos la ultima
y = dataset.iloc[:, -1].values# todas las filas solo la ultima columna

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [16]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [17]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data
# Cuidar los datos faltantes

In [18]:
from sklearn.impute import SimpleImputer # cargar libreria "SimpleImputer"
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')# asignar el metodo a remplazar los nan por la media (missing_values=np.nan, strategy='mean')
# strategies: ['mean', 'median', 'most_frequent', 'constant']
imputer.fit(X[:, 1:3])# tomamos los vlores numericos (all filas y las columnas 2 y 3)
X[:, 1:3] = imputer.transform(X[:, 1:3])# remplazamos en la mismas pociciones

In [9]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding categorical data
(Codificación de datos categóricos)

### Encoding the Independent Variable
(Codificación de la variable independiente)

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder # libreria de codificacion en caliente
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')# remainder='passthrough'>>> indica que mantenemos las columnas que no se aplico la codificacion
X = np.array(ct.fit_transform(X)) # con numpy agrupamos de nuevo los datos codificados 

In [20]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable
(Codificación de la variable dependiente)

In [21]:
from sklearn.preprocessing import LabelEncoder # importamos libreria 
le = LabelEncoder() # cargamos el objeto LabelEncoder()
y0 = y
y = le.fit_transform(y) # aplicamos la transformacion a Y

In [22]:
print(y0)
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set
(División del conjunto de datos en el conjunto de entrenamiento y el conjunto de prueba)

In [23]:
from sklearn.model_selection import train_test_split #libreria para dividir los datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [27]:
print(X_train)
print(len(X))
print(len(X_train))

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
10
8


In [28]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [31]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [32]:
print(y_test)

[0 1]


## Feature Scaling
(Escalado de funciones)

In [33]:
print(X_train[:, 3:])

[[38.77777777777778 52000.0]
 [40.0 63777.77777777778]
 [44.0 72000.0]
 [38.0 61000.0]
 [27.0 48000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [35.0 58000.0]]


* # Standardisation = (x - media(x) ) / (standar deviation(x))

* # Normalisation = (x - min(x) ) / (max(x) - min(x))

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() # creamos el objeto de estandarizacion 
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])# transformamos las columnas 3 y 4 del conjunto de entrenamiento
X_test[:, 3:] = sc.transform(X_test[:, 3:])# transformamos las columnas 3 y 4 del conjunto de testeo

In [35]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [36]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
